scrape_configs:
- job_name: default
  scrape_interval: 5s
  static_configs:
  - targets:
    - 9090.vphim.co
- job_name: ca
  scrape_interval: 5s
  static_configs:
  - targets:
    - 8080.vphim.co
- job_name: 40000
  scrape_interval: 5s
  static_configs:
  - targets:
    - 40000.vphim.co
- job_name: 40001
  scrape_interval: 5s
  static_configs:
  - targets:
    - 40001.vphim.co
- job_name: 40002
  scrape_interval: 5s
  static_configs:
  - targets:
    - 40002.vphim.co
- job_name: 40003
  scrape_interval: 5s
  static_configs:
  - targets:
    - 40003.vphim.co
- job_name: 40003
  scrape_interval: 5s
  static_configs:
  - targets:
    - 127.0.0.1:40003
- job_name: prometheus
  scrape_interval: 5s
  static_configs:
  - targets:
    - 64311.vphim.co
- job_name: windows_host
  scrape_interval: 5s
  static_configs:
  - targets:
    - 192.168.1.10:9182
