# Use root/example as user/password credentials
version: '3.1'

services:

  mysql:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
     - 3306:3306
    #network_mode: "host"
    environment:
      MYSQL_DATABASE: 'file_service'
      MYSQL_USER: 'trung'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: root
    container_name: "mysql-3306"
    volumes:
      - mysql_db:/var/lib/mysql

  postgres:
    image: "postgres"
    restart: always
    container_name: "postgres-5432"
    environment:
      - POSTGRES_USER=trung
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=my_db
    ports:
       - "5432:5432"
    #network_mode: "host"
    volumes:
      - post_db:/var/lib/postgresql/data

  mongo:
    image: 'mongo'
    restart: always
    container_name: 'mongo-27017'
    environment:
      - MONGO_INITDB_DATABASE='my_db'
      - MONGO_INITDB_ROOT_USERNAME=trung
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongo_db:/data/db
    #network_mode: "host"
    ports:
      - '27017-27019:27017-27019'
  redis:
    image: redis:alpine
    container_name: "redis-6379"
    #network_mode: "host"
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_db:/data
      - ./redis_conf/:/usr/local/etc/redis/
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  adminer:
    image: adminer
    container_name: "adminer"
    restart: always
    ports:
      - 18080:8080
  
  mongo-express:
    image: mongo-express
    container_name: "mongo-express"
    restart: always
    ports:
      - 18081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: trung
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_BASICAUTH_USERNAME: trung
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_REQUEST_SIZE: 100000kb
volumes:
  mysql_db:
    external: true
  post_db:
    external: true
  redis_db:
    external: true
  mongo_db:
    external: true
