# Use root/example as user/password credentials
version: '3.1'

services:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'my_db'
      MYSQL_USER: 'trung'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: trung
    container_name: "my_mysql"
    volumes:
      - mysql_db:/var/lib/mysql

  postgres:
    image: "postgres"
    restart: always
    container_name: "my_postgres"
    environment:
      - POSTGRES_USER=trung
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=my_db
    ports:
      - "5432:5432"
    volumes:
      - post_db:/var/lib/postgresql/data

  mongo:
    image: 'mongo'
    restart: always
    container_name: 'my_mongo'
    environment:
      - MONGO_INITDB_DATABASE='my_db'
      - MONGO_INITDB_ROOT_USERNAME=trung
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongo_db:/data/db
    ports:
      - '27017-27019:27017-27019'
  redis:
    image: redis:alpine
    container_name: "my_redis"
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_db:/data
      - ./conf:/usr/local/etc/redis
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  adminer:
    image: adminer
    restart: always
    ports:
      - 10000:8080
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 10001:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: trung
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_BASICAUTH_USERNAME: trung
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_REQUEST_SIZE: 100000kb
volumes:
  mysql_db:
    external: true
  post_db:
    external: true
  redis_db:
    external: true
  mongo_db:
    external: true
